[project]
name = 'bigmarket-dao'
description = 'Prediction markets on Stacks'
authors = []
telemetry = true
cache_dir = '.cache'

[contracts.clarity-bitcoin-lib-v5]
path = 'contracts/external/clarity-bitcoin-lib-v5.clar'
epoch = 2.0

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
