[project]
name = 'bigmarket-dao'
description = 'Prediction markets on Stacks'
authors = []
telemetry = true
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token'
[contracts.bdp000-bootstrap]
path = 'contracts/proposals/devnet/bdp000-bootstrap.clar'
clarity_version = 3
epoch = 3.0

[contracts.bigmarket-dao]
path = 'contracts/bigmarket-dao.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme000-0-governance-token]
path = 'contracts/extensions/bme000-0-governance-token.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme001-0-proposal-voting]
path = 'contracts/extensions/bme001-0-proposal-voting.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme003-0-core-proposals]
path = 'contracts/extensions/bme003-0-core-proposals.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme004-0-core-execute]
path = 'contracts/extensions/bme004-0-core-execute.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme006-0-treasury]
path = 'contracts/extensions/bme006-0-treasury.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme010-0-token-sale]
path = 'contracts/extensions/bme010-0-token-sale.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme021-0-market-voting]
path = 'contracts/extensions/bme021-0-market-voting.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme022-0-market-gating]
path = 'contracts/extensions/bme022-0-market-gating.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme023-0-market-bitcoin]
path = 'contracts/extensions/bme023-0-market-bitcoin.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme023-0-market-predicting]
path = 'contracts/extensions/bme023-0-market-predicting.clar'
clarity_version = 3
epoch = 3.0

[contracts.bme023-0-market-scalar]
path = 'contracts/extensions/bme023-0-market-scalar.clar'
clarity_version = 3
epoch = 3.0

[contracts.clarity-bitcoin-lib-v5]
path = 'contracts/external/clarity-bitcoin-lib-v5.clar'
clarity_version = 3
epoch = 3.0

[contracts.dia-oracle]
path = 'contracts/external/dia-oracle.clar'
clarity_version = 3
epoch = 3.0

[contracts.extension-trait]
path = 'contracts/traits/extension-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.governance-token-trait]
path = 'contracts/traits/governance-token-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.prediction-market-trait]
path = 'contracts/traits/prediction-market-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.proposal-trait]
path = 'contracts/traits/proposal-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.sbtc]
path = 'contracts/external/sbtc.clar'
clarity_version = 3
epoch = 3.0

[contracts.wrapped-stx]
path = 'contracts/external/wrapped-stx.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
