[project]
name = "bigmarket-dao"
description = 'Bitcoin Layer 2 DAO fork of Executor DAO'
authors = ['mijoco']
telemetry = false
cache_dir = '.cache'
clarity_version = 3
epoch = "3.0"

[project.cache_location]
path = ".cache"

#[repl.analysis]
#passes = ["check_checker"]
#strict = false
#trusted_sender = true
#trusted_caller = true
#callee_filter = true

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.sip010-ft-trait"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.sip009-nft-trait"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.wrapped-stx"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.sbtc"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.extension-trait"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.proposal-trait"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.prediction-market-trait"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.governance-token-trait"

[contracts.sip009-nft-trait]
path = "contracts/traits/sip009-nft-trait.clar"

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"

[contracts.prediction-market-trait]
path = "contracts/traits/prediction-market-trait.clar"

[contracts.governance-token-trait]
path = "contracts/traits/governance-token-trait.clar"

[contracts.wrapped-stx]
path = "contracts/external/wrapped-stx.clar"
clarity_version = 3
epoch = "3.0"

[contracts.sbtc]
path = "contracts/external/sbtc.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bitcoin-dao]
path = "contracts/bitcoin-dao.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde000-governance-token]
path = "contracts/extensions/bde000-governance-token.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde001-proposal-voting-tokenised]
path = "contracts/extensions/bde001-proposal-voting-tokenised.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde003-core-proposals-tokenised]
path = "contracts/extensions/bde003-core-proposals-tokenised.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde004-core-execute]
path = "contracts/extensions/bde004-core-execute.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde006-treasury]
path = "contracts/extensions/bde006-treasury.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde010-token-sale]
path = "contracts/extensions/bde010-token-sale.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde023-market-predicting]
path = "contracts/extensions/bde023-market-predicting.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde021-market-voting]
path = "contracts/extensions/bde021-market-voting.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde022-market-gating]
path = "contracts/extensions/bde022-market-gating.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp000-bootstrap]
path = "contracts/proposals/testnet/bdp000-bootstrap.clar"
clarity_version = 3
epoch = "3.0"
