[project]
name = 'bigmarket-dao'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST3VXT52QEQPZ5246A16RFNMR1PRJ96JK6YYX37N8.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = "SP3JP0N1ZXGASRJ0F7QAHWFPGTVK9T2XNXDB908Z.extension-trait"

[[project.requirements]]
contract_id = "SP3JP0N1ZXGASRJ0F7QAHWFPGTVK9T2XNXDB908Z.proposal-trait"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.wrapped-stx"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.sbtc"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.prediction-market-trait"

[[project.requirements]]
contract_id = "ST11804SFNTNRKZQBWB1R3F5YHEXSTXXEWZDXTMH6.governance-token-trait"


[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
clarity_version = 3
epoch = "3.0"

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
clarity_version = 3
epoch = "3.0"

[contracts.prediction-market-trait]
path = "contracts/traits/prediction-market-trait.clar"
clarity_version = 3
epoch = "3.0"

[contracts.governance-token-trait]
path = "contracts/traits/governance-token-trait.clar"
clarity_version = 3
epoch = "3.0"

[contracts.sbtc]
path = "contracts/external/sbtc.clar"
clarity_version = 3
epoch = "3.0"

[contracts.wrapped-stx]
path = "contracts/external/wrapped-stx.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bitcoin-dao]
path = "contracts/bitcoin-dao.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde000-governance-token]
path = "contracts/extensions/bde000-governance-token.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde001-proposal-voting-tokenised]
path = "contracts/extensions/bde001-proposal-voting-tokenised.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde003-core-proposals-tokenised]
path = "contracts/extensions/bde003-core-proposals-tokenised.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde004-core-execute]
path = "contracts/extensions/bde004-core-execute.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde006-treasury]
path = "contracts/extensions/bde006-treasury.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde010-token-sale]
path = "contracts/extensions/bde010-token-sale.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde023-market-predicting]
path = "contracts/extensions/bde023-market-predicting.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde021-market-voting]
path = "contracts/extensions/bde021-market-voting.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bde022-market-gating]
path = "contracts/extensions/bde022-market-gating.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp000-bootstrap]
path = "contracts/proposals/devnet/bdp000-bootstrap.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp000-core-team-sunset-height]
path = "contracts/proposals/devnet/bdp000-core-team-sunset-height.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-gating]
path = "contracts/proposals/devnet/bdp001-gating.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-gating-false]
path = "contracts/proposals/devnet/bdp001-gating-false.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-gating-true-testnet]
path = "contracts/proposals/devnet/bdp001-gating-true-testnet.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-market-fees]
path = "contracts/proposals/devnet/unit-tests/bdp001-market-fees.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-market-fees-1]
path = "contracts/proposals/devnet/unit-tests/bdp001-market-fees-1.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-reset-allocation]
path = "contracts/proposals/devnet/unit-tests/bdp001-reset-allocation.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-initialise-token-sale]
path = "contracts/proposals/devnet/unit-tests/bdp001-initialise-token-sale.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-advance-stage-1]
path = "contracts/proposals/devnet/unit-tests/bdp001-advance-stage-1.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-advance-stage-2]
path = "contracts/proposals/devnet/unit-tests/bdp001-advance-stage-2.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-advance-stage-3]
path = "contracts/proposals/devnet/unit-tests/bdp001-advance-stage-3.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-advance-stage-4]
path = "contracts/proposals/devnet/unit-tests/bdp001-advance-stage-4.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-advance-stage-5]
path = "contracts/proposals/devnet/unit-tests/bdp001-advance-stage-5.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-advance-stage-6]
path = "contracts/proposals/devnet/unit-tests/bdp001-advance-stage-6.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-advance-stage-7]
path = "contracts/proposals/devnet/unit-tests/bdp001-advance-stage-7.clar"
clarity_version = 3
epoch = "3.0"

[contracts.bdp001-cancel-stage]
path = "contracts/proposals/devnet/unit-tests/bdp001-cancel-stage.clar"
clarity_version = 3
epoch = "3.0"
